# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.2.4
group=net.somfunambulist
java_version=21
# Common
minecraft_version=1.21.1
mod_name=Thicket
mod_author=somfunambulist, Uraneptus
mod_id=thicket
license=GPL-3.0
credits=
description=Expanded forestry and woodworking in Minecraft.
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17
# Fabric
fabric_version=0.116.15+1.21.1
fabric_loader_version=0.19.3
# NeoForge
neoforge_version=21.1.244
neoforge_loader_version_range=[4,)

# Moonlight
moonlight_version=1.21.1-3.3.0
codecui_version=1.21.1-1.4.0
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
